### ISSUE TITLE
HStack count value returns wrong value

### ISSUE THREAD

**Issue by v-ahadke** [nalexn/ViewInspector#115]
We have few SwiftUI views in our codebase where we have some conditional checks which will decide whether to add view in HStack etc like below
```
struct HStackSampleContentView: View {
    var title: String?   
    var subtitle: String?
    var body: some View {
        HStack {
            if let formattedTitle = title  {
                Text(formattedTitle)
            }
            if let formattedSubtitle = subtitle {
                Text(formattedSubtitle)
            }
        }
        .padding(.top, 20)
    }
}
```

To test above view, we have below test

```
func testHstackContents() throws {
      let sut = HStackSampleContentView(title: nil, subtitle: nil)
      let hStack = try sut.inspect().hStack()
      XCTAssertNotNil(hStack)
      XCTAssertEqual(try hStack.padding().top, 20)
      XCTAssertEqual(hStack.count, 0)
}
```
But above test fails with ```XCTAssertEqual failed: ("2") is not equal to ("0")```. When we have title & subtitle value, ```XCTAssertEqual(hStack.count, 2)``` works correctly. Could you please have a look at it or am I missing something? 

Also I found a test [here](https://github.com/nalexn/ViewInspector/blob/82f5f29b0ddb3b7c2a1b9be366bfe4638ade3302/Tests/ViewInspectorTests/SwiftUI/OptionalViewTests.swift#L16) where `XCTAssertThrows` is used but its not accessible outside `ViewInspector` because func is `internal`. Do we have any specific API exposed which we can use in our tests to check if view is not part of view hierarchy instead of `XCTAssertThrows`?

**Comment by nalexn** [comment]
Hey @v-ahadke 

SwiftUI has a special view type `ConditionalView` for wrapping constructions like

```swift
if let formattedTitle = title  {
    Text(formattedTitle)
}
```

So when you ask `HStack` "how many views do you contain?", it actually says "2" because there are always two `ConditionalView` entities sitting there, regardless of the `if` statements inside of them.

So if you want to assure `HStack` contains exactly zero or one view, you actually have to try accessing the view at the index of the missing view and assert the library throws an error. The view indices are constant, that is, if the first view is missing, accessing it at index 0 will throw, but the present second view will remain available at its index 1.

To assure the expression throws an error, you can use `XCTAssertThrowsError` function, which is part of the standard toolset. `XCTAssertThrows` was added to the library and not exposed publicly for more fine-grained inner control over what exact exceptions are thrown in each specific case, you don't need that.

**Comment by v-ahadke** [comment]
Thank you @nalexn. Now I understand the reason behind test failure. After updating the test by accessing view at index & asserting using throw as below works perfectly

```XCTAssertThrowsError(try hStack.text(0))```
