### ISSUE TITLE
Test a ViewBuilder Crash

### ISSUE THREAD

**Issue by pjcau** [nalexn/ViewInspector#140]
HI, 

I should use a trick to the keyPath for didApper, so I write a struct 

```
struct TestingView<Content: View>: View {
    let content: Content
    var diDAppear: ((Self) -> Void)?

    init(@ViewBuilder content: () -> Content) {
        self.content = content()
    }

    var body: some View {
        content
            .onAppear {
                self.diDAppear?(self)
            }
    }
}

```

and after I can do a test 

```
func test_viewBuilder() {
        var sut = TestingView { AppView() }
        let exp = sut.on(\.diDAppear) { view in
            print("view is \(view)")
        }
        ViewHosting.host(view: sut)
        wait(for: [exp], timeout: 0.1)
    }
```

![Screenshot 2021-09-24 at 16 58 02](https://user-images.githubusercontent.com/1088176/134696373-1507d93e-e173-4c92-bbcb-019eedb96dfd.png)
)

So I looking a trick to cannot repeat the 
   
` internal var didAppear: ((Self) -> Void)?
`

in each views that I can test.

Do you have a news?

J

**Comment by nalexn** [comment]
Hey, I did some experiments with the sample code you have.

The problem is with referencing `Self` in the `var didAppear: ((Self) -> Void)?`, which is perfectly legit, however, in Xcode 13 it crashes if the type has a generic parameter.

That is, when I replace `Self` with just `Inspectable`, the code does not crash., so I believe this is a bug in the Swift compiler.

The good news is that the [alternative inspection approach](https://github.com/nalexn/ViewInspector/blob/master/guide.md#approach-2) with `Inspection` does not crash:

```swift
struct TestingView<Content: View>: View, Inspectable {
    let content: Content
    let inspection = Inspection<Self>()

    init(@ViewBuilder content: () -> Content) {
        self.content = content()
    }

    var body: some View {
        content
            .onReceive(inspection.notice) { self.inspection.visit(self, $0) }
    }
}

func test_viewBuilder() {
    let sut = TestingView { AnyView(Text("22")) }
    let exp = sut.inspection.inspect { view in
        print("view is \(view)")
    }
    ViewHosting.host(view: sut)
    wait(for: [exp], timeout: 0.1)
}
```
