### ISSUE TITLE
run without adding to live code

### ISSUE THREAD

**Issue by bukira** [nalexn/ViewInspector#153]
Can you use viewinspector without adding 

internal let inspection = Inspection<Self>() //for testing UI
 
and 

.onReceive(inspection.notice) { self.inspection.visit(self, $0) }

to production code?
As these 2 lines corrupt with webRTC project

**Comment by nalexn** [comment]
Hey, you can try using conditional compilation (compiler flags) so that the same code would use view inspector in `debug` but get removed for `prod` mode.

Something similar to what is suggested for [watchOS inspection guide](https://github.com/nalexn/ViewInspector/blob/master/guide_watchOS.md), that references [this file](https://github.com/nalexn/ViewInspector/blob/master/.watchOS/watchOS-Ext/watchOSApp%2BTestable.swift).

**Comment by bukira** [comment]
Legend , I need for just testing in test target

**Comment by bukira** [comment]
So would I use the same watchOS code but change to iOS if def? Or is that watchOS specific code and I just need to put an
#if DEBUG 
Before the code in each View?

**Comment by nalexn** [comment]
Realized my previous advice wasn't on point. Could you explain how exactly "these 2 lines corrupt with webRTC project"?

**Comment by bukira** [comment]
Your answer worked for me, I don’t know how they corrupt as such, if I have those 2 lines in build code then the first voip call has no audio, if I remove those lines then voip calls have audio, it’s very weird. But as viewinspector is only required for UI tests then I added an if def for test target,

I added -DTESTBUILD to my other linker flags in my test target and then added 

#if TESTTARGET
Viewinspector code 
#endif

Before both lines in all my views and works great so your advice was spot on with complier flags 

Cheers
