### ISSUE TITLE
How to build failing test for change in view

### ISSUE THREAD

**Issue by babbage** [nalexn/ViewInspector#181]
I have a test I wrote to confirm a bug that I found, where the failure to include an `@Published` on an array in my viewModel meant that the view would not immediately update when a method was called that added an item to the array, even though the viewModel data had changed. Functionally, what would be seen was that when another change was made, the expected initial change would be visible as the `ForEach` that was accessing that array would also be updated.

I wrote the following test that I expected to fail, that counted the number of rows in the section before the method was called, then called the method that should result in a row being added, and then examining the new row count:

```
// Setup
let viewModel = await ViewModelType()
let view = await ViewType(viewModel: viewModel)
let rows = try view.inspect().findAll(ItemRowType.self)
let baselineCount = rows.count

// Process under test
await viewModel.actions?.addItem()

// Test expectations
let finalRows = try view.inspect().findAll(ItemRowType.self)
let finalCount = finalRows.count

XCTAssertTrue(finalCount == baselineCount + 1, "Expected \(baselineCount + 1) final count but found \(finalCount)")
```

Unfortunately, this test did not fail even when the bug was present. It would correctly find three rows in `baselineCount` (the ViewModel was initialised with some existing data), and find four rows present in `finalCount`, while the bug remained functionally.

My guess is that most likely, calling the second `view.inspect()` results in the view being updated? Given my bug was a failure for the view to be updated, this thus hides the problem I was trying to test, which is the failure for the view to be updated when the data model changed.

Is there another mechanism in ViewInspector that would let me test this? For example, is there a mechanism to observe calls to update the view or similar, so that I could assert that such an update has been called, after my `await viewModel.actions?.addItem()` is called?

**Comment by nalexn** [comment]
Hey @babbage , 
`@Published` property wrapper allows SwiftUI to observe changes in properties (your array) on the ObservableObject (your viewModel). If you omit it, the object and the array stay functional, but mutations remain unnoticed by the SwiftUI render engine.

If we take out the SwiftUI for ease of understanding, your test is equivalent to the following:
```swift
class ViewModel {
     var counter: Int = 0
}
struct View {
    let viewModel: ViewModel
    func readValue() -> Int {
        return viewModel.counter
    }
}

// ---- test:

let viewModel = ViewModel()
let view = View(viewModel: viewModel)
XCAssertEqual(view.readValue(), 0)
viewModel.counter ++
XCAssertEqual(view.readValue(), 1)
```

This test succeeds because viewModel is a reference type, it does not need any fancy way to propagate the changes.

I've come up with a way to verify what you want, it's not very concise, but you can explore how to optimize the approach yourself. In your test scope you'll need to define a helper view that'll serve as a wrapper for your test view and that'd count how many times the view is redrawn:

```swift
// In your test file:
struct RedrawCounterView: View, Inspectable {
    @StateObject var viewModel: ViewModelType
    let redrawCounter: Binding<Int>
    
    var body: some View {
        redrawCounter.wrappedValue += 1
        return ViewType(viewModel: viewModel)
    }
}

// The test:

func testPublishedIsPresent() throws {
    let viewModel = ViewModelType()
    let counter = Binding<Int>(wrappedValue: 0)
    let sut = RedrawCounterView(viewModel: viewModel, redrawCounter: counter)
    let exp = XCTestExpectation(description: #function)
    DispatchQueue.main.async {
        viewModel.actions?.addItem()
        DispatchQueue.main.async {
            XCTAssertEqual(counter.wrappedValue, 2)
            exp.fulfill()
        }
    }
    ViewHosting.host(view: sut)
    wait(for: [exp], timeout: 0.3)
}
```
In the test, you assert the total redraw counter is 2 (one when you host the view, and the other one when the array is mutated).
If you remove `@Published` the test will fail, because the redraw counter will be 1.

**Comment by nalexn** [comment]
Feel free to reopen the issue if this did not help
