### ISSUE TITLE
0.9.2 - Not available in Cocoapods

### ISSUE THREAD

**Issue by mkieselmann** [nalexn/ViewInspector#211]
The latest version 0.9.2 has not made it to the Cocoapods repo. https://cocoapods.org/pods/ViewInspector still shows v0.9.1.
This forces us to use the git repo and tag configuration in Cocoapods, which breaks in some setup.
Would appreciate any help or hints how to push 0.9.2.

Thanks

**Comment by nalexn** [comment]
The problem is that I need to transfer pod ownership to my new email address (I lost access to the one used in cocoapods). I reached out 2 times through their [pod claim form](https://blog.cocoapods.org/Claim-Your-Pods/) in a span of months, DMed a few cocoapod maintainers in Twitter, asked publicly if anyone knows who I can reach out to for my inquiry - no luck in any direction, no one knows who's managing it.

**Comment by lockieluke** [comment]
at the meantime you can install the pod with:
```ruby
pod 'ViewInspector', :git => 'https://github.com/nalexn/ViewInspector.git', :branch => 'master'
```

**Comment by nalexn** [comment]
0.9.3 is now available in cocoapods.
