### ISSUE TITLE
Not working though both values are same

### ISSUE THREAD

**Issue by jagothjdey** [nalexn/ViewInspector#26]
import XCTest
import ViewInspector

@testable import RandomListProject

extension ContentView: Inspectable { }

class ContentViewTests: XCTestCase {

    func testStringValue() throws {
        let sut = ContentView()
        let value = try sut.inspect().text().string()
        XCTAssertEqual(value, "Hello, world!")
    }
}

import SwiftUI
struct ContentView: View {
         var body: some View {
                Text("Hello, World!")
        }
}

above is my testcase class and content view. Still its showing me following error?

XCTAssertEqual failed: ("Optional("Hello, World!")") is not equal to ("Optional("Hello, world!")")

**Comment by nalexn** [comment]
Hm.. That's weird. Since the string was extracted correctly: `Optional("Hello, World!")`, my guess is that this is related to your dev environment (Xcode / Swift version). Also, your project may have an extension for Optional that shadows the default Equatable protocol conformance for Optional.
This test is basically equivalent to the following:
```swift
let value1: String? = "Hello, World!"
let value2: String? = "Hello, World!"
XCTAssertEqual(value1, value2)
```
Which obviously should succeed in a healthy system setup

**Comment by jagothjdey** [comment]
Thanks. I will get back to you after some checkings.

**Comment by TimAEllis** [comment]
May be unrelated, but noticed that the case of `w` in world is different (upper vs lowercase)
```
XCTAssertEqual(value, "Hello, world!")
```
and
```
Text("Hello, World!")
```

**Comment by nalexn** [comment]
Haha, nice catch Tim!

**Comment by jagothjdey** [comment]
Oh my goodness. Do you know what I was really looking for a solution.
Thanks a lot 😎😛
