### ISSUE TITLE
Undefined symbol: nominal type descriptor for project.ContentViewTest

### ISSUE THREAD

**Issue by teeneoapp** [nalexn/ViewInspector#27]
Hi, I would like to use ViewInspector to test my views in Swift UI.

When I try to launch my test, 3 errors appears:
- Undefined symbol: nominal type descriptor for project.ContentViewTest
- Undefined symbol: protocol conformance descriptor for project.ContentViewTest : SwiftUI.View in project
- Undefined symbol: type metadata for project.ContentViewTest

**Can someone help me please ?**

projectUITests.swift

    import XCTest
    import ViewInspector
    @testable import project

    extension ContentViewTest: Inspectable { }

    final class ContentViewTests: XCTestCase {

        func testStringValue() throws { 
            let sut = ContentViewTest()
            let value = try sut.inspect().text().string()
            XCTAssertEqual(value, "Hello, world!")
        }
    }

ContentViewTest.swift

    import SwiftUI

    struct ContentViewTest: View {
        var body: some View {
            Text("Hello, world!")
        }
    }

**Comment by SeanMcTex** [comment]
I'm seeing a similar issue. If anyone is able to get this sorted, I'd be glad to know about it!

**Comment by SeanMcTex** [comment]
Aha! In my case, this was resolved by actually following the installation instructions correctly. ;) I'd failed to select the test target when I was installing the package the first time:

"Hit Next two times, under Add to Target *select your test target*. There is no need to add it to the build target."

**Comment by teeneoapp** [comment]
Yeah I think I failed my installation
I will try again, thanks for your help ;)

**Comment by fangorn-treebeard-1962** [comment]
For noobies like me out there, ViewInspector should be added as a package dependency to the Unit Test target, not the UI Tests target.

I know this issue is closed, but maybe this will help someone. I'm new to XCode and Swift development, but at least with XCode 15+, when you create a new Swift project "with Tests", you get a Unit Test group, and UI Test group.  I mistakenly associated "Views" with UI, and spent 24+ hrs trying to figure out why the linker couldn't find symbols. Once I found an example working project and tore apart the project file, I finally realized "Unit Test", not "UI Test".  Hope this helps someone.
