### ISSUE TITLE
Test background color of views

### ISSUE THREAD

**Issue by Ganyev** [nalexn/ViewInspector#48]
Hello, 
Is there any ways to test background color (or any other colors) of views (e.g. Text().background) ?

**Comment by nalexn** [comment]
Hey! The `Color` view has mysteriously sneaked out of the scope! It's added in v0.4.8

So you can either compare the color value directly:

```swift
let sut = try view.inspect().text().background().color().value()
XCTAssertEqual(sut, Color.red)
```

compare the name:

```
let sut = try view.inspect().text().background().color().name()
XCTAssertEqual(sut, "my_color")
```

or get the actual RGBA values:

```
let sut = try view.inspect().text().background().color().rgba()
XCTAssertEqual(sut.red, 0.5)
```

Note, that the `Color(red:, green:, blue:)` and some other initializers use `.sRGB` color space as the default parameter. Because of this, the inner RGB representation may be different to the values you provide in the `init`, i.e. `red` value may be not the same as the `red` used in `init`
