### ISSUE TITLE
Find (still) causes EnvironmentObject crashes

### ISSUE THREAD

**Issue by Tyler-Keith-Thompson** [nalexn/ViewInspector#99]
So I had opened an [issue](https://github.com/nalexn/ViewInspector/issues/87) a while ago about how Find causes custom views to crash if they have an `@EnvironmentObject`. 

It got closed as fixed but it's still very much crashing for `find`, for `findAll` and everything else I've tried. The only way to not have a crash is to directly tie your tests to your view hierarchy and use the `.view()` method.

**Comment by nalexn** [comment]
Sorry to hear that it still doesn't work for you. The crash originates from SwiftUI when the library tries to extract the body and the view is missing any `EnvironmentObject`. I added a check that throws an error with the details instead of allowing SwiftUI to crash. This will allow you to locate the issue, but the root problem is not in the `find` or `findAll` - one of the views you have in the hierarchy is missing `EnvironmentObject` injection. Consider adding `.environmentObject(...)` calls for all the objects you use before inspecting the hierarchy. That is, if you had `let sut = MyCustomView()` and `try sut.inspect().find(...)`, you need to do injection first: `let sut = MyCustomView().environmentObject(...)`

**Comment by Tyler-Keith-Thompson** [comment]
I can't inject an environmentObject on a nested view. The problem is like this
```swift
struct ViewIWantToTest: View {
    @EnvironmentObject var thingICanTest: SomeEnvironmentObject
    let inspection = Inspection<Self>()
    
    var body: some View {
        VStack {
            SomeOtherView()
            Text("Text I want to find")
        }.onRecieve(inspection.notice) { self.inspection.visit(self, $0) }
    }
}

struct SomeOtherView: View {
    @EnvironmentObject var thingThatCrashes: SomeEnvironmentObject
    let inspection = Inspection<Self>()
    
    var body: some View {
        VStack {
            if thingThatCrashes.someProperty { //this line crashes when testing ViewIWantToTest
                Text("Extra Content")
            }
        }.onRecieve(inspection.notice) { self.inspection.visit(self, $0) }
    }
}
```

Test that crashes:
```swift
    let sut = try ViewIWantToTest()
    let exp = sut.inspection.inspect { view in 
        let text = try view.find(ViewType.Text.self) //because SomeOtherView has environment object and comes *before* the text
    }
    
    ViewHosting.host(sut.environmentObject(SomeEnvironmentObject())
    wait(for: [exp], timeout: 1.5)
    
```

Test that works:
```swift
    let sut = try ViewIWantToTest()
    let exp = sut.inspection.inspect { view in 
        let text = try view.vStack().text(1)
        let alsoWorks = try view.vStack().view(SomeOtherView.self, 0)
    }
    
    ViewHosting.host(sut.environmentObject(SomeEnvironmentObject())
    wait(for: [exp], timeout: 1.5)
```

This is why I am blaming `find`. If I know the exact hierarchy (which unfortunately couples my tests to irrelevant code, like the VStack) then it works just fine, if I use `find` then it crashes. It's good that `find` now throws instead of crashes, at least my tests will give better output, but it's unfortunate that finding the text can't work because the text is *after* the custom view.

**Comment by nalexn** [comment]
> I can't inject an environmentObject on a nested view

And you don't have to - the library is doing it now when you uncover the view from the parent. If your nested view is missing some other EnvObject that's not being used by the parent view - you'd need to add injection to the parent.

Copied and run your sample - it does not crash for me, I get the "Text I want to find" from the "find"

**Comment by Tyler-Keith-Thompson** [comment]
Huh, you're right. As of 0.7.3 I don't have this problem. I really thought it was still an issue in 0.7.2. Regardless it definitely isn't now. 

Thanks for all your very fast feedback! This library is likely to become pretty important to our company, so I've been trying to put it through its paces, we may not be able to inspect *everything* but we can get really far, your hard work is greatly appreciated.

**Comment by tete1030** [comment]
I encountered the same problem in 0.9.1. After some digging, I find that there seems a bug introducing from 0.7.0 (the version is consistent with the time point when this bug started appearing)

I find that my environmentObject is instead set in `medium.environmentModifiers`, due to this code:

https://github.com/nalexn/ViewInspector/blob/6b88c4ec1fa20cf38f2138052e63c8e79df5d76e/Sources/ViewInspector/SwiftUI/CustomViewModifier.swift#L71-L77

Shouldn't an EnvironmentObject be a NSObject? a typo?  @nalexn
